"""Increase message content size

Revision ID: d49882ecda84
Revises: a01d095b221e
Create Date: 2024-04-23 15:34:46.177049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd49882ecda84'
down_revision: Union[str, None] = 'a01d095b221e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=5000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.String(length=5000),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###
